### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ThorstenBux** [augmentmy-world/artoolkitX.js#1] opened 2019-05-23 00:42 UTC
from @kalwalt

@ThorstenBux thank you! i tested but can't find some files... the artoolkitX.api.js needs a file artoolkitx.js that doen't exist or is not in place. Must build before? but in this case something went wrong with the path:

if i run git submodule update --init i need to change the path inside .gitmodules:
+ [submodule "Source/extras/artoolkitx"]
- [submodule "Source/Extras/artoolkitx"]
+ path = Source/extras/artoolkitx
- path = Source/Extras/artoolkitx
url = git@github.com:artoolkitx/artoolkitx.git
then i run build.sh in the Source folder:

./build.sh
+ test 0 -gt 0
+ '[' ']'
+ echo 'start download of libs'
start download of libs
+ cd /home/walter/kalwalt-github/artoolkitX.js/Source
+ install_plugin
++ cat ../version.txt
cat: ../version.txt: File o directory non esistente
+ VERSION=
probably needs a branch or files not yet in place?

**Comment by ThorstenBux** [comment] 2019-05-23 00:43
Yes the build is just working for dev mode. The final build that is pulling the dependencies is work in progess.
```build.sh --dev```

**Comment by kalwalt** [comment] 2019-05-23 13:07
I continue the discussion from https://github.com/artoolkitx/artoolkitx/issues/83 
Thank you for the clarification @ThorstenBux , after manually configuring  with cmake, the build process stop with this error:

```bash
make
[ 58%] Built target AR
[ 68%] Built target ARUtil
[ 69%] Building C object ARX/ARVideo/CMakeFiles/ARVideo.dir/cparamSearch.c.o
clang: warning: argument unused during compilation: '-msse' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse3' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mssse3' [-Wunused-command-line-argument]
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
In file included from /usr/include/stdio.h:41:
/usr/include/bits/libio.h:463:4: warning: type specifier missing, defaults to
      'int' [-Wimplicit-int]
                        _IO_va_list, int *__restrict);
                        ^
/usr/include/bits/libio.h:48:21: note: expanded from macro '_IO_va_list'
#define _IO_va_list _G_va_list
                    ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
In file included from /usr/include/stdio.h:41:
/usr/include/bits/libio.h:465:5: warning: type specifier missing, defaults to
      'int' [-Wimplicit-int]
                         _IO_va_list);
                         ^
/usr/include/bits/libio.h:48:21: note: expanded from macro '_IO_va_list'
#define _IO_va_list _G_va_list
                    ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:46:9: error: unknown type name '__gnuc_va_list'
typedef _G_va_list va_list;
        ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:328:8: error: unknown type name '__gnuc_va_list'
                     _G_va_list __arg);
                     ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:333:54: error: unknown type name '__gnuc_va_list'
extern int vprintf (const char *__restrict __format, _G_va_list __arg);
                                                     ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:336:8: error: unknown type name '__gnuc_va_list'
                     _G_va_list __arg) __THROWNL;
                     ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:345:42: error: unknown type name '__gnuc_va_list'
                      const char *__restrict __format, _G_va_list __arg)
                                                       ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:353:9: error: unknown type name '__gnuc_va_list'
                      _G_va_list __arg)
                      ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:366:8: error: unknown type name '__gnuc_va_list'
                     _G_va_list __arg)
                     ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:421:7: error: unknown type name '__gnuc_va_list'
                    _G_va_list __arg)
                    ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:428:53: error: unknown type name '__gnuc_va_list'
extern int vscanf (const char *__restrict __format, _G_va_list __arg)
                                                    ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:433:40: error: unknown type name '__gnuc_va_list'
                    const char *__restrict __format, _G_va_list __arg)
                                                     ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:53:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/../AR/include/ARX/AR/ar.h:64:
/usr/include/stdio.h:831:8: error: unknown type name '__gnuc_va_list'
                            _G_va_list __args)
                            ^
/usr/include/bits/_G_config.h:51:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list
                   ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:183:
In file included from /usr/include/bits/posix1_lim.h:160:
In file included from /usr/include/bits/local_lim.h:38:
/usr/include/linux/limits.h:7:9: warning: 'NGROUPS_MAX' macro redefined
      [-Wmacro-redefined]
#define NGROUPS_MAX    65536    /* supplemental group IDs are available */
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:51:9: note: 
      previous definition is here
#define NGROUPS_MAX 32
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:183:
In file included from /usr/include/bits/posix1_lim.h:160:
/usr/include/bits/local_lim.h:64:9: warning: 'PTHREAD_KEYS_MAX' macro redefined
      [-Wmacro-redefined]
#define PTHREAD_KEYS_MAX        1024
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:63:9: note: 
      previous definition is here
#define PTHREAD_KEYS_MAX 128
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:183:
In file included from /usr/include/bits/posix1_lim.h:160:
/usr/include/bits/local_lim.h:69:9: warning: 'PTHREAD_DESTRUCTOR_ITERATIONS'
      macro redefined [-Wmacro-redefined]
#define PTHREAD_DESTRUCTOR_ITERATIONS   _POSIX_THREAD_DESTRUCTOR_ITERATIONS
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:65:9: note: 
      previous definition is here
#define PTHREAD_DESTRUCTOR_ITERATIONS 4
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:183:
In file included from /usr/include/bits/posix1_lim.h:160:
/usr/include/bits/local_lim.h:81:9: warning: 'PTHREAD_STACK_MIN' macro redefined
      [-Wmacro-redefined]
#define PTHREAD_STACK_MIN       16384
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:64:9: note: 
      previous definition is here
#define PTHREAD_STACK_MIN 2048
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:183:
In file included from /usr/include/bits/posix1_lim.h:160:
/usr/include/bits/local_lim.h:84:9: warning: 'DELAYTIMER_MAX' macro redefined
      [-Wmacro-redefined]
#define DELAYTIMER_MAX  2147483647
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:68:9: note: 
      previous definition is here
#define DELAYTIMER_MAX 0x7fffffff
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:183:
In file included from /usr/include/bits/posix1_lim.h:160:
/usr/include/bits/local_lim.h:93:9: warning: 'HOST_NAME_MAX' macro redefined
      [-Wmacro-redefined]
#define HOST_NAME_MAX           64
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:59:9: note: 
      previous definition is here
#define HOST_NAME_MAX 255
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:183:
In file included from /usr/include/bits/posix1_lim.h:160:
/usr/include/bits/local_lim.h:99:9: warning: 'SEM_VALUE_MAX' macro redefined
      [-Wmacro-redefined]
#define SEM_VALUE_MAX   (2147483647)
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:66:9: note: 
      previous definition is here
#define SEM_VALUE_MAX 0x7fffffff
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:187:
/usr/include/bits/posix2_lim.h:88:9: warning: 'RE_DUP_MAX' macro redefined
      [-Wmacro-redefined]
#define RE_DUP_MAX (0x7fff)
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:82:9: note: 
      previous definition is here
#define RE_DUP_MAX 255
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:62:9: warning: '_XOPEN_IOV_MAX' macro redefined
      [-Wmacro-redefined]
#define _XOPEN_IOV_MAX  _POSIX_UIO_MAXIOV
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:150:9: note: 
      previous definition is here
#define _XOPEN_IOV_MAX          16
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:66:10: warning: 'IOV_MAX' macro redefined
      [-Wmacro-redefined]
# define IOV_MAX __IOV_MAX
         ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:53:9: note: 
      previous definition is here
#define IOV_MAX 1024
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:73:9: warning: 'NL_ARGMAX' macro redefined
      [-Wmacro-redefined]
#define NL_ARGMAX       _POSIX_ARG_MAX
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:84:9: note: 
      previous definition is here
#define NL_ARGMAX 9
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:76:9: warning: 'NL_LANGMAX' macro redefined
      [-Wmacro-redefined]
#define NL_LANGMAX      _POSIX2_LINE_MAX
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:85:9: note: 
      previous definition is here
#define NL_LANGMAX 32
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:79:9: warning: 'NL_MSGMAX' macro redefined
      [-Wmacro-redefined]
#define NL_MSGMAX       INT_MAX
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:86:9: note: 
      previous definition is here
#define NL_MSGMAX 32767
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:84:10: warning: 'NL_NMAX' macro redefined
      [-Wmacro-redefined]
# define NL_NMAX        INT_MAX
         ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:95:9: note: 
      previous definition is here
#define NL_NMAX 16
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:88:9: warning: 'NL_SETMAX' macro redefined
      [-Wmacro-redefined]
#define NL_SETMAX       INT_MAX
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:87:9: note: 
      previous definition is here
#define NL_SETMAX 255
        ^
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.c:41:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/cparamSearch.h:42:
In file included from /home/walter/kalwalt-github/artoolkitx/Source/ARX/ARVideo/include/ARX/ARVideo/video.h:55:
In file included from /usr/include/limits.h:191:
/usr/include/bits/xopen_lim.h:91:9: warning: 'NL_TEXTMAX' macro redefined
      [-Wmacro-redefined]
#define NL_TEXTMAX      INT_MAX
        ^
/home/walter/emsdk/emscripten/1.38.31/system/include/libc/limits.h:88:9: note: 
      previous definition is here
#define NL_TEXTMAX 2048
        ^
18 warnings and 11 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
ARX/ARVideo/CMakeFiles/ARVideo.dir/build.make:63: recipe for target 'ARX/ARVideo/CMakeFiles/ARVideo.dir/cparamSearch.c.o' failed
make[2]: *** [ARX/ARVideo/CMakeFiles/ARVideo.dir/cparamSearch.c.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'ARX/ARVideo/CMakeFiles/ARVideo.dir/all' failed
make[1]: *** [ARX/ARVideo/CMakeFiles/ARVideo.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```
it seems an issue with the compiler, not sure if it come from my side ( i missed something?)  or something else...

**Comment by kalwalt** [comment] 2019-05-23 13:26
do not consider the previous comment i was trying to build the lib only with cmake gui, this probably is not correct...

**Comment by kalwalt** [comment] 2019-05-27 16:06
@ThorstenBux i managed to build the artoolkitx.js lib, with cmake-gui and choosing the emscripten toolchain. There are some consideration at least for my OS (linux) .
The error above was caused because conflicting files ( c includes already include by emscripten i think), and the fact some of my includes jpeg and other libs point to the same C include folder.  and at the end i had to add also:
`-s ERROR_ON_UNDEFINED_SYMBOLS=0` to pass a linking error caused by the jpeg lib. ( does it striclty necessary ?)
i created a PR here https://github.com/augmentmy-world/artoolkitX.js/pull/2.

**Comment by ThorstenBux** [comment] 2019-08-10 23:57
fixed, you might need to update the submodule artoolkitX

https://github.com/augmentmy-world/artoolkitx/commit/4ce65570a4d1541de582abfcbf69f8386f8493dd

**Comment by kalwalt** [comment] 2019-08-11 12:36
Thank you @ThorstenBux  that is magic! I tried and i compiled but i had to do a little modification in a 
 ARX/ARUtil CMakeLists.txt : https://github.com/augmentmy-world/artoolkitx/blob/4ce65570a4d1541de582abfcbf69f8386f8493dd/Source/ARX/ARUtil/CMakeLists.txt#L9-L17 

i change to:

```cmake
else()
        find_path(
            STB_INCLUDE_DIR
            stb_image 
            NAMES stb_image.h stb_image_write.h
	    PATHS ${PROJECT_SOURCE_DIR}/depends/emscripten/include
        )
        add_definitions("-s USE_ZLIB=1")
    endif()
```
and adding the files `stb_image.h stb_image_write.h` in the `/depends/emscripten/include/stb_image` folder.

**Comment by kalwalt** [comment] 2019-08-11 14:31
@ThorstenBux i opened this PR https://github.com/augmentmy-world/artoolkitx/pull/2 to fix this issue

**Comment by kalwalt** [comment] 2019-08-20 14:45
the PR https://github.com/augmentmy-world/artoolkitx/pull/2 is merged in the emscripten branch and solved the issue. and also we can now download the libraries with the build script, instructions in the Readme file https://github.com/augmentmy-world/artoolkitX.js

**Closed as completed by kalwalt** 2019-08-20 14:45 UTC
Labels: good first issue
